---
- hosts: instantjobs
  gather_facts: false

  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup: # aka gather_facts

  tasks:
    - include_vars: "group_vars/vhosts.yml"

  roles:
   - common
   - phpenv
   - waldenit.nginx 
   - waldenit.mysql
   - waldenit.apache2
   - firewall
