---
- name: phpenv | Load the OS specific variables
  include_vars: "{{ansible_os_family | lower}}.yml"

- debug: var=build_dependencies 

- name: phpenv | Install php-build dependencies (Debian)
  apt: pkg={{ item }} state=present install_recommends=no
  with_items: 
    - re2c
    - libgd-dev # gd
    - libjpeg-dev # jpeg
    - libpng12-dev # png
    - zlib1g-dev # zlib
    - libkrb5-dev # kerberos
    - libssl-dev # openssl
    - libmcrypt-dev # mcrypt
    - libxml2-dev # soap xml-reader xmlrpc
    - libxslt1-dev # xsl
    - libcurl4-openssl-dev # curl
    - libtidy-dev # tidy
    - libmysqlclient-dev # mysql
    - libpq-dev # postgresql
    - libsqlite3-dev # sqlite
    - libreadline-dev # readline
  # extras
    - libbz2-dev # bzip

  sudo: true
