- lineinfile:
    dest: '/etc/default/locale'
    regexp: '^LC_ALL='
    line: 'LC_ALL=en_US.UTF-8'

- apt_repository:
    repo: 'ppa:ondrej/apache2'

- name: update apt packages
  apt: >
    update_cache=yes
    cache_valid_time=3600

- name: upgrade apt packages
  apt: upgrade=yes
