---

- stat: path=/usr/local/phpenv/versions/{{item}}/etc/php-fpm.d/www.conf.default
  register: confd
  with_items: phpenv_versions


- name: Activate php-fpm configuration file (if present)
  command: creates="/usr/local/phpenv/versions/{{item}}/etc/php-fpm.conf" removes="/usr/local/phpenv/versions/{{item}}/etc/php-fpm.conf.default"  mv /usr/local/phpenv/versions/{{item}}/etc/php-fpm.conf.default /usr/local/phpenv/versions/{{item}}/etc/php-fpm.conf
  with_items: phpenv_versions 

- name: Activate pool configuration file (if present)
  command: creates="/usr/local/phpenv/versions/{{item.1}}/etc/php-fpm.d/www.conf" removes="/usr/local/phpenv/versions/{{item.1}}/etc/php-fpm.d/www.conf.default"  mv /usr/local/phpenv/versions/{{item.1}}/etc/php-fpm.d/www.conf.default /usr/local/phpenv/versions/{{item.1}}/etc/php-fpm.d/www.conf
  when: confd.results.{{item.0}}.stat.exists == True
  with_indexed_items: phpenv_versions 

- lineinfile:
    dest: /usr/local/phpenv/versions/{{item.1}}/etc/php-fpm.d/www.conf
    regexp: '^listen '
    line: "listen = /var/run/php-fpm-{{item.1}}.sock"
    state: present
  with_indexed_items: phpenv_versions
  when: confd.results.{{item.0}}.stat.exists == True
 
- lineinfile:
    dest: /usr/local/phpenv/versions/{{item.1}}/etc/php-fpm.conf
    regexp: '^listen '
    line: "listen = /var/run/php-fpm-{{item.1}}.sock"
    state: present
  with_indexed_items: phpenv_versions
  when: confd.results.{{item.0}}.stat.exists == False
 
- lineinfile:
    dest: /usr/local/phpenv/versions/{{item.1}}/etc/php-fpm.d/www.conf
    regexp: '^user ='
    line: "user = {{phpfpm_user}}"
    state: present
  with_indexed_items: phpenv_versions
  when: confd.results.{{item.0}}.stat.exists == True
 
- lineinfile:
    dest: /usr/local/phpenv/versions/{{item.1}}/etc/php-fpm.conf
    regexp: '^user ='
    line: "user = {{phpfpm_user}}"
    state: present
  with_indexed_items: phpenv_versions
  when: confd.results.{{item.0}}.stat.exists == False
 
- lineinfile:
    dest: /usr/local/phpenv/versions/{{item.1}}/etc/php-fpm.d/www.conf
    regexp: '^group ='
    line: "group = {{phpfpm_group}}"
    state: present
  with_indexed_items: phpenv_versions
  when: confd.results.{{item.0}}.stat.exists == True
 
- lineinfile:
    dest: /usr/local/phpenv/versions/{{item.1}}/etc/php-fpm.conf
    regexp: '^group ='
    line: "group = {{phpfpm_group}}" 
    state: present
  with_indexed_items: phpenv_versions
  when: confd.results.{{item.0}}.stat.exists == False

- lineinfile:
    dest: /usr/local/phpenv/versions/{{item.1}}/etc/php-fpm.d/www.conf
    regexp: '^\[www\]'
    line: "[www-{{item.1}}]"
    state: present
  with_indexed_items: phpenv_versions
  when: confd.results.{{item.0}}.stat.exists == True
 
- lineinfile:
    dest: /usr/local/phpenv/versions/{{item.1}}/etc/php-fpm.conf
    regexp: '^\[www\]'
    line: "[www-{{item.1}}]" 
    state: present
  with_indexed_items: phpenv_versions
  when: confd.results.{{item.0}}.stat.exists == False

- template: 
    dest: /etc/init.d/php-fpm-{{item}} 
    src:  php-fpm-init.j2  
    mode: 0755
  with_items: phpenv_versions

- name: "restart php-fpm {{item}}"
  command:  "/etc/init.d/php-fpm-{{item}} restart"
  with_items: phpenv_versions

